feat: 모임 앨범(홈) UI 레이아웃 구현
dnd-side-project/dnd-11th-6-frontend pull request #15
Opened 2024-07-30 15:51 UTC by Dawon00

## 변경사항
- 모임 앨범(메인 페이지)의 UI를 구현했습니다.

## 세부내용
- `meeting/[meetingId]` 경로로 라우팅을 설정했습니다.
- 경로명을 `/create-meeting` 에 맞춰 `/entry-meeting` 으로 수정했습니다.

## 참고사항
- 디자인과 기능적인 요소는 제외했습니다.
- 라우팅 경로는 논의 후 수정해도 좋을 것 같습니다.

## 연관 이슈
#12

2024-07-31 09:20 UTC, jiji-hoon96 reviewed
리뷰 수정부탁드립니다!

2024-07-31 09:20 UTC, jiji-hoon96 commented on src/app/meeting/[meetingId]/page.tsx
> +function MeetingPage({ params }: { params: { meetingId: string } }) {
meetingId는 전역으로 관리해야 될 필요가 있어 보입니다! store로 분리하는 건 어떠할까요!?

2024-07-31 09:20 UTC, jiji-hoon96 commented on src/app/meeting/[meetingId]/page.tsx
> +  const meetingId = params.meetingId as string
as를 이용한 강제 타입 형변환은 타입을 숨기기 때문에 타입 추론할 수 없기때문에 지양해야됩니다!

2024-07-31 13:16 UTC, Dawon00 commented on src/app/meeting/[meetingId]/page.tsx
> +function MeetingPage({ params }: { params: { meetingId: string } }) {
좋은 의견 감사합니다! 전역 상태로 옮겨보겠습니다 :)

2024-07-31 13:35 UTC, Dawon00 commented on src/app/meeting/[meetingId]/page.tsx
> +  const meetingId = params.meetingId as string
앗 그렇군요 쓰지 않는 방향으로 수정해보겠습니다!!

2024-08-01 11:13 UTC, jiji-hoon96 requested changes
리뷰 남겨두었습니다!

2024-08-01 11:13 UTC, jiji-hoon96 commented on src/app/entry-meeting/page.tsx
> +import MeetingInfo from './_components/MeetingInfo'
_components 하위 것들 한번에 import하는 방법 [여기](https://github.com/dnd-side-project/dnd-11th-6-frontend/pull/16/commits/d636778c20d918b8ffb2ed3bac1a56ec76623b60) 참고해서 변경하는게 가독성이 좋아보여요!

2024-08-01 11:13 UTC, jiji-hoon96 commented on src/app/meeting/[meetingId]/MeetingPageClient.tsx
> +function MeetingPageClient({ meetingId, photos }: MeetingPageClientProps) {
store에 meetingId 가 있는데, 넘기는 이유가 있을까요!?
photos도 동일하게 store로 작업하시는게 좋아보여요!

2024-08-01 11:13 UTC, jiji-hoon96 commented on src/stores/useMeetingStore.ts
> +type MeetingStore = {
여기도 state랑 action으로 분리하는 것은 어떠할까요!?

[공식문서 가이드](https://docs.pmnd.rs/zustand/guides/updating-state) 참고하시면 좋을 것 같습니다! 

이번주에 만나면 type, interface 중에 어떤 것을 사용하는 것이 적합한지 의논해봐요!

2024-08-01 13:18 UTC, Dawon00 commented on src/app/entry-meeting/page.tsx
> +import MeetingInfo from './_components/MeetingInfo'
넵 반영하겠습니다!

2024-08-01 13:59 UTC, Dawon00 commented on src/stores/useMeetingStore.ts
> +type MeetingStore = {
분리하면 더 좋을 것 같아요! 수정해보겠습니다

2024-08-01 14:10 UTC, jiji-hoon96 approved these changes

2024-08-02 03:14 UTC, merged